export const authConstants = { 
    LOGOUT: "LOGOUT",
    LOGIN: "LOGIN",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE",
    REGISTER_REQUEST: "REGISTER_REQUEST"
};

export const messagesConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};

export const recipesConstants = {
    GET_RECIPES: 'GET_RECIPES',
    GET_SUCCESS: 'GET_SUCCESS',
    GET_FAILURE: 'GET_FAILURE',

    GET_RECIPE: 'GET_RECIPE',
    GET_RECIPE_SUCCESS: 'GET_RECIPE_SUCCESS',
    GET_RECIPE_FAILURE: 'GET_RECIPE_FAILURE',

    DELETE_RECIPE: "DELETE_RECIPE",
    DELETE_RECIPE_SUCCESS: "DELETE_RECIPE_SUCCESS", 
    DELETE_RECIPE_FAILURE: "DELETE_RECIPE_FAILURE",

    CREATE_RECIPE: "CREATE_RECIPE",
    CREATE_RECIPE_SUCCESS: "CREATE_RECIPE_SUCCESS",
    CREATE_RECIPE_FAILURE: "CREATE_RECIPE_FAILURE",

    UPDATE_RECIPE: "UPDATE_RECIPE",
    UPDATE_RECIPE_SUCCESS: "UPDATE_RECIPE_SUCCESS",
    UPDATE_RECIPE_FAILURE: "UPDATE_RECIPE_FAILURE",
};